### ISSUE TITLE
Alexa version issue

### ISSUE THREAD

**Issue by nickm324** [thehookup/Motorized_MQTT_Blinds#1]
I dont think the Alexa version in the releases page is actually they Alexa version.
Have you tested this Alexa version? I am getting all kinds of weird results. First the Flasher wouldn't work, as soon as I would click the FLASH button it would instantly say FLASH COMPLETE in a small dialog. So I then decided to use NodeMCU-PyFlasher, which worked. I finally got it to show up on my phone as Blinds Setup so I connected to that AP, set the SSID, password and left 12 in the box. It then said it was going to attempt to connect to the network and that was it no other interaction on the phone from that point. So after I just went ahead and hit the reset NodeMCU to let it reboot although I cant tell what its doing if anything. So then Opened the Alexa App and did a discover devices and chose type as OTHER since I have no idea what type of device its going to show up as. 1 device showed up called "12" as a LIGHT, that is connected via HUE HUB and the type is LIGHT. And it says to say Alexa turn off or on the LIGHT to control it. Then I decided to look at the source code so I downloaded that and opened it up all I see is a bunch of stuff about MQTT and everything in that source looks like its trying to use an MQTT broker to do what ever its trying to do. 
Any insight to what I am doing wrong would be greatly appreciated.﻿

**Comment by thehookup** [comment]
Resolution posted on youtube comments:

@Nick Marino Ah, yeah, it's the same as mine.  You have mistaken configurable fields for labels.  The "12" should be typed where it says "Rotations 12 Recommended" in gray. SSID should be typed where it says SSID and your password should be below that.  Where you currently have "12" is the spot to type the alexa invocation name.  When you click on a field the gray text disappears.  This isn't my design, it's a pre-made library called WiFiConfig.﻿

Closing this issue.
