### ISSUE TITLE
Be sure to cut solder bridge in motors!

### ISSUE THREAD

**Issue by mllockwood** [thehookup/Motorized_MQTT_Blinds#11]
I know that it's covered in the YouTube video, but it should probably be added to the list of written instructions.  For those like me that watched the video last week, received our components from Amazon this week, and finally got some time to work on the project... and forgot about that one IMPORTANT step.

Be sure to open up the motor housing and cut the board to eliminate the connection of the red wire on the circuit board.  If you don't the motors will get VERY hot and can be dangerous.

**Comment by thehookup** [comment]
Added to the readme, thanks.
