### ISSUE TITLE
Motor not turning

### ISSUE THREAD

**Issue by cvetand** [thehookup/Motorized_MQTT_Blinds#12]
I followed the wiring diagram but I can't get the motor to work with the DRV8825. I'm thinking it is a power issue as the specs for the DRV8825 list its minimum operational voltage as 8V where I am getting ~4.2V from the nodemcu and even less with the buck converter. Is the buck converter used to convert the 5V from the nodemcu to 12V or is there a separate power supply that isn't listed?

**Comment by cmille34** [comment]
The way I understand the diagrams and the way I have it working is splitting the wires coming from the 12v power supply with one pair of the wires going to the buck converter to convert the 12v from the power supply into a 5v source for the nodeMCU and the DRV8825, then take the other spliced 12v power wires and run them also to the pins on the DRV8825.  Essentially you are providing a 5v and 12v source to the DRV8825.  The motor will use the 12v pins and the driver itself will use the 5v provided to is (I think). The diagram helped me immensely. 
https://github.com/thehookup/Motorized_MQTT_Blinds/blob/master/Schematic.jpg

**Comment by cvetand** [comment]
That makes sense. I completely missed the 12V power supply in the parts list so the "12V Supply" in the schematic seemed like it was the output of the buck converter. After adding it, it all started to work. Thanks!
