### ISSUE TITLE
"MQTT Only with WiFi Manager" bin file

### ISSUE THREAD

**Issue by tung256** [thehookup/Motorized_MQTT_Blinds#17]
hello, i love your bin file since i couldnt compile my own!
now, i see "12" position is not good for my blinds. so instead of use 2 wires and physically reset, how can i access the website where i originally set things up work?

**Comment by thehookup** [comment]
Unfortunately not possible. You'll need to connect pin D1 to ground during the boot process to get the AP to broadcast again.
