### ISSUE TITLE
Running Blind Motors in Series

### ISSUE THREAD

**Issue by lithium-ap** [thehookup/Motorized_MQTT_Blinds#23]
What is the best path for wiring the stepper motors in series. I would like to power the nodemcu and stepper driver from PoE with the least amount of parts. Can the stepper drive be used across 2-3 blind motors? Can one stepper driver be used to power two motors effectively?

**Comment by christensonautohome** [comment]
I used 1 stepper driver per motor and have the stepper for each motor up in the blinds.

**Comment by thehookup** [comment]
You should have a stepper for each motor, you can run many drivers in parallel from a single nodemcu.
