### ISSUE TITLE
Motor Keep shifting position 2 or 3° Anti CW in each cycle.

### ISSUE THREAD

**Issue by vinodnx** [thehookup/Motorized_MQTT_Blinds#31]
Hello All,
Motor Keep increasing position 2 or 3° Anti-CW and decreasing 2 to 3° CW in each cycle. Please suggest any recommendations.

Please refer below video for more details

https://www.youtube.com/watch?v=lweSv-2Ar-U&feature=youtu.be

**Comment by poggerb** [comment]
Vinodnx, could it be due to the motor sometimes missing steps? 

This article suggests driver current settings can cause missing steps.  

https://www.makerguides.com/drv8825-stepper-motor-driver-arduino-tutorial/

**Comment by thehookup** [comment]
Which version of the code are you using vinodnx?

**Comment by vinodnx** [comment]
Hello Friend,

I was using a servo motor, which is not the same as your stepper motor.
sorry to bother you

Regards
Vinod
