### ISSUE TITLE
My nodemcu won't connect to my MQTT server running on my VM

### ISSUE THREAD

**Issue by furlough1** [thehookup/Motorized_MQTT_Blinds#32]
NodeMCU won't connect to MQTT:  Attempting MQTT connection...failed, rc=2 try again in 5 seconds. In the "Open serial monitor" I don't see a port for the MQTT server. How do I add a port or reset the NodeMCU?

**Comment by thehookup** [comment]
Connect pin D1 to ground to reset your settings and return to the WiFi portal.
