### ISSUE TITLE
Alexa_MQTT_Homeassistant

### ISSUE THREAD

**Issue by jenniferlee1818** [thehookup/Motorized_MQTT_Blinds#33]
I made a new release which is working great for me.  It syncs between Alexa and Homeassistant the state of the blinds no matter which is used to control them.  I'm afraid I'm not an Arduino coder, so hoping someone will take a look at my hacky Alexa_MQTT_Homeassistant.ino to make sure I haven't done it all wrong.  I know that just because it works, doesn't mean that I have done it correctly!

https://github.com/echojjj/Motorized_MQTT_Blinds/releases/tag/v1.0

[Alexa_MQTT_Homeassistant.zip](https://github.com/thehookup/Motorized_MQTT_Blinds/files/4638520/Alexa_MQTT_Homeassistant.zip)

    cover:
      - platform: mqtt
        name: "South Blinds"
        command_topic: "south-blinds/blindsCommand" 
        set_position_topic: "south-blinds/positionCommand"
        position_topic: "south-blinds/positionState"
        state_topic: "south-blinds/positionState"
        retain: true
        payload_open: "ON"
        payload_close: "OFF"
        position_open: 14
        position_closed: 0

**Comment by nuaimat** [comment]
Thank you, i got it to work but the mcu was not getting discovered by Alexa, 
after following https://github.com/vintlabs/fauxmoESP/issues/39  it got discovered. thanks a lot 👍🏼
