### ISSUE TITLE
Fault Pin Connected to 5v?

### ISSUE THREAD

**Issue by ryancasler** [thehookup/Motorized_MQTT_Blinds#37]
I am wondering why you have the DRV8825's Fault pin connected to 5v.  From what I can see from other schematics that use this driver, that pin is never connected to the VCC of the microcontroller.  The datasheet says that it is output low when there is a fault detected.  Why would you want to short out the power supply if there is a fault detected?  Won't that burn out your supply?

**Comment by jenniferlee1818** [comment]
I was wondering the same thing.  I think the DRV8825 GND is to common to the microcontroller ground, and that be the mistake in the wiring diagram, but it does work even with 5v to fault pin.

**Comment by ryancasler** [comment]
And doesn't without the 5v to the fault pin.  I am wondering if it has something to do with using the Enable pin rather than the sleep pin to power down the motor controller when not moving.  I decided to just try it since I have 5 of each and only 3 windows where I'd possibly use them.  So, even if I blew one, I'd still have one as a backup.  :)  Glad I wasn't the only one that was confused by that.

**Comment by thehookup** [comment]
That is really strange.  The reason I wired it that way is that I'm used to working with A4988 drivers that take Vdd on that pin.  I've always heard/read that the DRV8825 can be wired interchangeably with the A4988, so that's what I did.  It hasn't caused any issues for me.  It looks like the only other pin to use to supply Vdd is the RST pin?  That's strange to me.

**Comment by ryancasler** [comment]
Yeah, it is definitely required to have the pin connected to 5v to get it to work.  I just can't figure out why either.  I it must have something to do with using the EN pin instead of the SLEEP pin to shut the board down.  

When it comes to the tiny current adjustment on the board, when you said in the 12 o'clock position, what did you mean?  when oriented in which way?  Did you mean half way between min and max?  I have only 3 blinds to automate and 5 motors but I'd rather save them for other screwups later on than to blow one up unnecessarily.

**Comment by jenniferlee1818** [comment]
![Untitled-1](https://user-images.githubusercontent.com/44507767/86978551-6bdc0000-c13c-11ea-9a24-27d6135a9d02.jpg)

[https://www.pololu.com/product/2132](url)

**Comment by echojjj** [comment]
@ryancasler the position of the pot would be at 12:00 when the flat edge is at 6:00.  look closely for the flat edge.

**Comment by jenniferlee1818** [comment]
@ryancasler the pot is at 12:00 when the flat edge is at 6:00.  look closely for the flat edge.  here's a picture of a pot at 12:00
![Untitled-2](https://user-images.githubusercontent.com/44507767/86978414-1e5f9300-c13c-11ea-9151-e4b1745b59c0.jpg)

**Comment by softtechs1** [comment]
I got everything wired per the diagram, programed MCU and getting data from MQTT. Just can't get the motor the move at all. Does the GND on the DRV8825 need to be connected to the GND of the MCU? From looking at the wiring on the A4988 driver, its connected to the microcontroller.

**Comment by ryancasler** [comment]
How are you powering the board?  Are you using a buck converter like in the diagram or are you using a 12v supply and a 5v supply.  I have mine wired like the pic and it works.  You just have to make sure the two grounds are tied together somewhere.  No ground, no current flow.

**Comment by softtechs1** [comment]
Thanks so much for responding! I purchased everything from the amazon links and wired as in the pic schematic. Using the 12v power supply, connected to the input side of the buck converter. Ran another 12v wire pair to connect the DRV8825’s UMOT/GRN pins. NodeMCU 12E gets power from the buck’s 6V output side. From the buck converter output side, I also have another 6V pair, which only the + from the buck converter is connected to the DRV8825 FLT pin, the negative is not connected as per the schematic, which is confusing. Everything else the schematic should be straight forward (Step, Dir, EN and 4 Motor wires). From what’s in the schematic, I don’t understand how the grounds tie together?
See my test bench photos.

![Buck-NodeMCU-Wiring](https://user-images.githubusercontent.com/76082026/179908458-0b0ac9d7-e953-4104-9dc7-561123a81fa9.jpg)
![DRV8825-Wiring](https://user-images.githubusercontent.com/76082026/179908474-fc753f79-96bc-4fc7-975b-7a99572bc14b.jpg)

**Comment by ryancasler** [comment]
First of all, the output of the buck converter should be set to 5v.  Not 6.  
Second, how do you have the wires coming out of the Buck converter.  one side is + and the other is -.  So you need one from each side to the board.  You have two of the wires for the motor backwards.   The orange and pink should be pink-orange.
What type of 12v power supply are you using?  How many amps does it put out? Have you adjusted the current limiter on the DRV?  If that is all the way down, your motors won't move.
If you disconnect the buck converter's + line and just keep the gnd attached, you can plug in your board to your PC and see the output of the Serial log so you can try and see what is happening.  That way you can tell if it is able to connect to your wifi and actually receive the MQTT message.

**Comment by softtechs1** [comment]
@ryancasler I got this all working by replacing a bad DRV8825. Seems I received a bad batch along with motors. Installed 2 blinds so far and working on the 3 more. Thanks!
