### ISSUE TITLE
This is awesome. That is all.

### ISSUE THREAD

**Issue by chadbailey59** [thehookup/Motorized_MQTT_Blinds#43]
I hate that the "thanks" that most people get for doing open source work is an endless stream of problems in the form of GitHub issues. :) I'd wanted a 3D printer for a while, but I finally used this project as justification to buy one. 11 months of printing golden emoji poops later, I finally got around to doing this.

And it's totally awesome. Thank you for putting the effort into making the video and sharing the code. This kind of thing is what makes it fun to be a nerd.

**Comment by thehookup** [comment]
Haha, thanks Chad.
