### ISSUE TITLE
hex connector

### ISSUE THREAD

**Issue by umairyounus** [thehookup/Motorized_MQTT_Blinds#44]
Hi, 

Thanks for a great job. Is there any chance you can share scad file for hex connector? I need a 5.5mm adaptor.

**Comment by nuaimat** [comment]
Hi, 

I needed the same, here you go, it's modulized you can modify it easily, 
https://github.com/nuaimat/Motorized_MQTT_Blinds/blob/master/BlindsAdapter6mmHex.scad

**Comment by umairyounus** [comment]
perfect, thank you.
