### ISSUE TITLE
Blinds_CONFIGURE:1:83: fatal error: SimpleTimer.h

### ISSUE THREAD

**Issue by jrsmith77** [thehookup/Motorized_MQTT_Blinds#46]
I'm getting this error when trying to verify/compile the sketch. I'm very new to this altogether, so bare with me.
  I have tried pointing to different URLS, and also attempted to download the files locally and point to them. Still no luck. Anyone else experience this and know how to resolve?

Arduino: 1.8.13 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 57600"

Blinds_CONFIGURE:1:83: fatal error: SimpleTimer.h: No such file or directory

 #include <SimpleTimer.h>    //https://github.com/vigneshankar/Simple-Timer-Library

                                                                                   ^

compilation terminated.

exit status 1

SimpleTimer.h: No such file or directory

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by jrsmith77** [comment]
Issue was ignorance on my part.

**Comment by richcoliver** [comment]
My ignorance too but what was the fix please ?
