### ISSUE TITLE
PCB Walkthrough?

### ISSUE THREAD

**Issue by petereit** [thehookup/Motorized_MQTT_Blinds#63]
I have 4 blinds in my sunroom that I'd love to automate using Dave Morris's Quad Blind PCBs. The Blind Controller and Blind Motor boards make sense to me, but I'm not sure how the third PCB, the "Main Power From Supplies" board fits into the project.

Can someone give me a rundown, a diagram or a link to his project page?

**Comment by rustypasini** [comment]
Did you ever get a response to your question?

**Comment by petereit** [comment]
No. I just started with Rob‘s controller PCB layout, added two RJ45 connectors and ran 4 flat CAT6E cables to 4 motor controller boards. All 4 of my blinds are working great!

**Comment by furlough1** [comment]
No, I didn’t

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
