### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by theone964** [thehookup/Motorized_MQTT_Blinds#68]
Hello,
I have installed both versions of the Alexa Only version and i have used serial monitor to see that it has been connected to my wifi, I have also logged into my router and confirmed a new "ESP....." device there. I have tried to get Alexa to discover the device via Voice, and via the app by using it a Light> Other and Light>Phillips Hue and just Other but I cannot get Alexa to discover the NodeMCU no matter what I try. in the "Unique Alexa ID" I called it "Master Blinds" in case that makes any difference.

Thank you for any help

**Comment by thehookup** [comment]
I uploaded a new version to fix discovery issues here: https://github.com/thehookup/Motorized_MQTT_Blinds/releases/tag/Alexa_No_Hub

(select the .bin that is called [Updated_Alexa_Only_Blinds.bin]
