### ISSUE TITLE
Having Trouble with variables

### ISSUE THREAD

**Issue by morgancrawford6** [thehookup/Motorized_MQTT_Blinds#7]
Not sure what I am doing wrong. This is the error  get

Arduino: 1.8.9 (Mac OS X), Board: "Generic ESP8266 Module, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), ck, 26 MHz, 40MHz, DOUT (compatible), 512K (no SPIFFS), 2, nonos-sdk 2.2.1 (legacy), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Blinds_CONFIGURE_Portal_Alexa:36:35: error: 'D6' was not declared in this scope
 #define STEPPER_DIR_PIN           D6
                                   ^
/Users/Morgan/Desktop/Motorized_MQTT_Blinds-ee901ad7f0b51b0aa66704f191ce5e89c597226d/Blinds_CONFIGURE_Portal_Alexa/Blinds_CONFIGURE_Portal_Alexa.ino:51:51: note: in expansion of macro 'STEPPER_DIR_PIN'
 AH_EasyDriver shadeStepper(STEPPER_STEPS_PER_REV, STEPPER_DIR_PIN ,STEPPER_STEP_PIN,STEPPER_MICROSTEP_1_PIN,STEPPER_MICROSTEP_2_PIN,STEPPER_SLEEP_PIN);
                                                   ^
Blinds_CONFIGURE_Portal_Alexa:37:35: error: 'D7' was not declared in this scope
 #define STEPPER_STEP_PIN          D7
                                   ^
/Users/Morgan/Desktop/Motorized_MQTT_Blinds-ee901ad7f0b51b0aa66704f191ce5e89c597226d/Blinds_CONFIGURE_Portal_Alexa/Blinds_CONFIGURE_Portal_Alexa.ino:51:68: note: in expansion of macro 'STEPPER_STEP_PIN'
 AH_EasyDriver shadeStepper(STEPPER_STEPS_PER_REV, STEPPER_DIR_PIN ,STEPPER_STEP_PIN,STEPPER_MICROSTEP_1_PIN,STEPPER_MICROSTEP_2_PIN,STEPPER_SLEEP_PIN);
                                                                    ^
Blinds_CONFIGURE_Portal_Alexa:38:35: error: 'D5' was not declared in this scope
 #define STEPPER_SLEEP_PIN         D5
                                   ^
/Users/Morgan/Desktop/Motorized_MQTT_Blinds-ee901ad7f0b51b0aa66704f191ce5e89c597226d/Blinds_CONFIGURE_Portal_Alexa/Blinds_CONFIGURE_Portal_Alexa.ino:51:133: note: in expansion of macro 'STEPPER_SLEEP_PIN'
 AH_EasyDriver shadeStepper(STEPPER_STEPS_PER_REV, STEPPER_DIR_PIN ,STEPPER_STEP_PIN,STEPPER_MICROSTEP_1_PIN,STEPPER_MICROSTEP_2_PIN,STEPPER_SLEEP_PIN);
                                                                                                                                     ^
/Users/Morgan/Desktop/Motorized_MQTT_Blinds-ee901ad7f0b51b0aa66704f191ce5e89c597226d/Blinds_CONFIGURE_Portal_Alexa/Blinds_CONFIGURE_Portal_Alexa.ino: In function 'void configPortal()':
Blinds_CONFIGURE_Portal_Alexa:157:18: error: 'D1' was not declared in this scope
   if(digitalRead(D1) == LOW)
                  ^
/Users/Morgan/Desktop/Motorized_MQTT_Blinds-ee901ad7f0b51b0aa66704f191ce5e89c597226d/Blinds_CONFIGURE_Portal_Alexa/Blinds_CONFIGURE_Portal_Alexa.ino: In function 'void setup()':
Blinds_CONFIGURE_Portal_Alexa:267:11: error: 'D1' was not declared in this scope
   pinMode(D1, INPUT_PULLUP);
           ^
exit status 1
'D6' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by thehookup** [comment]
You are trying to flash using the "Generic ESP8266" board definition, not the NodeMCU, select nodemcu and the D6 and other definitions will be there.
