### ISSUE TITLE
One NodeMCU for 3 blinds

### ISSUE THREAD

**Issue by TurboTronix** [thehookup/Motorized_MQTT_Blinds#8]
Is it possible to control 3 blinds with on NodeMCU using other pins for the other 2 blinds? I have a bay-window with 3 blinds so was wondering if that was possible.

**Comment by TurboTronix** [comment]
Also can this work with zebra still blinds?

**Comment by cmille34** [comment]
You should be able to.  I have 2 blinds being controlled off the same pin and it works fine. If you wanted to control (3) separate stepper motors in (3) blinds you would need (9) PINs on the NodeMCU.  There should be enough pins to do that.  Just my 2 cents though - I'm not the author, just a big fan that really enjoyed following the instructions and automating 2 of our living room blinds.

**Comment by thehookup** [comment]
It's easy to do if you don't want them to be individually controlled, just wire the 3 stepper drivers in parallel.  If you want separate control you'll need to fork the code and do a bit of modification.
