### ISSUE TITLE
using Covers.yaml

### ISSUE THREAD

**Issue by TurboTronix** [thehookup/Motorized_MQTT_Blinds#9]
How can I add this cover inside my covers.yaml file? The way you have it written doesn't work...

This is what I have in my covers.yaml:

 - platform: template
   covers:
     garage_big_door:
 

How would I add this blind into it?

Also when I type the IP address of the NodeMCU in my browser I get: 

This site can’t be reached 192.168.X.X refused to connect.

**Comment by TurboTronix** [comment]
OK my MQTT log in hassio shows that the nodemcu was connected however it also shows:

Client BlindsMCU has exceeded timeout, disconnecting.

**Comment by TurboTronix** [comment]
Nevermind got it to work...

**Comment by tung256** [comment]
i think the way he has it was for configuration.yaml file right?
